export interface BusRecord {
    COMPANY_CODE: string,
    ROUTE_ID: number,
    ROUTE_NAMEC: string,
    ROUTE_NAMES: string,
    ROUTE_NAMEE: string,
    JOURNEY_TIME: number,
    ROUTE_TYPE: number,
    SERVICE_MODE: number,
    SPECIAL_TYPE: number,
    LOC_START_NAMEC: string,
    LOC_END_NAMEC: string,
    LOC_START_NAMEE: string,
    LOC_END_NAMEE: string,
    LOC_START_NAMES: string,
    LOC_END_NAMES: string,
    FULL_FARE: number,
    HYPERLINK_C: string,
    HYPERLINK_S: string,
    HYPERLINK_E: string,

    Bus: string,
    ROUTE_SEQ: string,
    STOP_SEQ: string,
    STOP_ID: number,
    STOP_PICK_DROP: string,
    STOP_NAMEC: string,
    STOP_NAMEE: string
}